# Copyright (c) 2026 An_172N
# 此代码根据GPLv3.0许可证授权


import SCRIPT.LOGIC.FRIEND.SPRITE.BASE as Base
from SCRIPT.LOGIC.FRIEND.SPRITE.BULLET import Bullet
from SCRIPT.LOGIC.FRIEND.SPRITE.BRICK import Brick
from SCRIPT.LOGIC.FRIEND.SPRITE.BARRAGE import Barrage
from SCRIPT.LOGIC.FRIEND.SPRITE.ITEM import Item
from SCRIPT.LOGIC.FRIEND.SPRITE.LINE import Line
from SCRIPT.LOGIC.FRIEND.SPRITE.PARTICLE import Particle

from SCRIPT.LOGIC.FRIEND.HUMAN.KLI import DecisionPoint
from SCRIPT.LOGIC.FRIEND.HUMAN.ONO import Ono
from SCRIPT.LOGIC.FRIEND.HUMAN.HRO import Hro
from SCRIPT.LOGIC.FRIEND.HUMAN.NRE import Nre
from SCRIPT.LOGIC.FRIEND.HUMAN.QDI import Qdi
from SCRIPT.LOGIC.FRIEND.HUMAN.KLI import Kli

import SCRIPT.LOGIC.SPRITE.PLANE as PlaneMgr
import SCRIPT.LOGIC.SPRITE.BULLET as BulletMgr
import SCRIPT.LOGIC.SPRITE.ITEM as ItemMgr
import SCRIPT.LOGIC.SPRITE.BRICK as BrickMgr
import SCRIPT.LOGIC.SPRITE.BARRAGE as BarrageMgr
import SCRIPT.LOGIC.SPRITE.PARTICLE as ParticleMgr

import SCRIPT.LOGIC.PROCESS.STAGE as StageMgr
import SCRIPT.LOGIC.PROCESS.GUI as GUI
import SCRIPT.LOGIC.PROCESS.KEY as Key
import SCRIPT.LOGIC.PROCESS.RESET as Reset