from SCRIPT.LOGIC.FRIEND.HUMAN.KLI import Kli
from SCRIPT.LOGIC.FRIEND.HUMAN.ONO import Ono
from SCRIPT.LOGIC.FRIEND.HUMAN.HRO import Hro
from SCRIPT.LOGIC.FRIEND.HUMAN.NRE import Nre

from SCRIPT.LOGIC.FRIEND.BASE import Base
from SCRIPT.LOGIC.FRIEND.HUMAN.KLI import DecPt